### ISSUE TITLE
I want to add a Bluetooth serial port module.

### ISSUE THREAD

**Issue by BG7UHS** [mcore1976/cc1101-tool#10]
I want to add a Bluetooth serial module, so that I can get rid of the bondage of USB cable.
![Screenshot_20230808-123306_淘宝](https://github.com/mcore1976/cc1101-tool/assets/25344138/01103c4e-9277-4fc3-b046-7e5305eba416)
![16914697257391742538137898041880](https://github.com/mcore1976/cc1101-tool/assets/25344138/f59e5d19-9187-4635-8799-2578940f971a)

**Comment by mcore1976** [comment]
good idea, but you need o connect to TX/RX lines of your Arduino board ( TXO/RXI lines) to your Bluetooth adapter. 

Also  Arduino Pro Micro you would need to use different Serial Port number in setup() function :  Serial1

https://www.arduino.cc/reference/en/language/functions/communication/serial/

you need to change all the commands in the source code

from **Serial.**XXXXX

to 

**Serial1.**XXXX

like this 

void setup(){ 
    Serial1.begin(9600);
}

void loop(){
    Serial1.print("HelloWorld");
}

It can be done with Find&Replace in the Notepad application..

**Comment by BG7UHS** [comment]
Thank you very much. I plan to use rp2040 with better performance.I'll consult you then.

**Comment by mcore1976** [comment]
Try ESP8266 wifi version, just posted yesterday. It allows wireless remote telnet connection (f.ex. using ConnectBot on Android)  and has exactly the same features as wired one.
