### ISSUE TITLE
The scan command didn't get any feedback.

### ISSUE THREAD

**Issue by BG7UHS** [mcore1976/cc1101-tool#11]
The scan command didn't get any feedback.
Esp32 and pro Micro both have the same problem.
![Screenshot_20230810-084703_Serial_USB_Terminal](https://github.com/mcore1976/cc1101-tool/assets/25344138/20641c27-a483-4a23-8199-4b856a236191)

**Comment by mcore1976** [comment]
You shoulkd narrow the band for searching like

scan 314 316 

or even 

scan 314 315

scan 315 316

scan function requires RF signal to be constantly available therefore keyfob must be pressed for at least 30 seconds.

**Comment by mcore1976** [comment]
explained above. If looking for wider band I would suggest to use RTL SDR USB dongle and SDRSharp application to find out the peak frequency. Scan function is only for finetuning the frequency spot
