### ISSUE TITLE
Question about preamble

### ISSUE THREAD

**Issue by lhofinger** [mcore1976/cc1101-tool#12]
Hello,
I'm testing cc1101-tool to open a door. When I decode the original signal with URH, I see a preamble of fffffe
Is it possible to set custom preamble? If not, how to disable completely preamble (and all other added bytes: sync, CRC...) ?
Thanks!

**Comment by mcore1976** [comment]
Hi, custom preamble may be set when using CC1101 in packet mode not the RAW mode.  It is 16 bit values (2 bytes)

Preamble is called a "syncword" in CC1101 terminology and following commands are used to configure it 


setsyncword <LOW, HIGH>      // Set sync word. Must be the same for the transmitter and receiver. (Syncword high, Syncword low)

setsyncmode  <sync mode>     

Sync mode = 0 -> No preamble/sync. 
1 = 16 sync word bits detected. 
2 = 16/16 sync word bits detected. 
3 = 30/32 sync word bits detected. 
4 = No preamble/sync, carrier-sense above threshold. 
5 = 15/16 + carrier-sense above threshold. 
6 = 16/16 + carrier-sense above threshold. 
7 = 30/32 + carrier-sense above threshold.
