### ISSUE TITLE
I have cc1101 red module name HW863

### ISSUE THREAD

**Issue by gg7200** [mcore1976/cc1101-tool#15]
I have this red module hw863 and it's not working with board I tried esp32 nodemcu arduino pro micro, nano but not working I also change cc1101 module but again it's not working please help if u know why it is not woking

**Comment by mcore1976** [comment]
You have full description of this module in this document : https://github.com/mcore1976/cc1101-tool/blob/main/AS07-M1101S.pdf  
the only difference is the naming of MISO pin which is GDO1 here.  Others already confirmed it is working so you must have messed your cabling.
It may happen that your HW863 board is broken as well.

**Comment by AlistairXX** [comment]
How did you connect its headers. Because they are very tiny. Only possible solution I see is unsoldering them and attaching wires.
