### ISSUE TITLE
showbit command incomplete data

### ISSUE THREAD

**Issue by jps1x2** [mcore1976/cc1101-tool#17]
Hi!

First of all thank you very much for your tool, i am working with it and i have mixed esp8266 ap+telnetServer code with esp32 code and i can use it on my esp32-wrover-dev connected with telnet on my smartphone.

I am trying to capture timing too, on recraw and rxraw, and i saw that showbit command is not working fine because:

1. You take 32 bytes from bigrecordingbuffer variable.
2. It is converted to hex string with 64 characters length.
3. Later the code only converts and displays the first 32 characters of this string and not 64 characters.

Example:
File: cc1101-tool-esp32-wroom.ino
Line 838: for (setting = 0; setting < 32 ; setting++)
correct: for (setting = 0; setting < 64 ; setting++)

Regards

Jps1x2

**Comment by mcore1976** [comment]
Thanks for pointing this out. I have just fixed all the source codes. I hope you are having a good time playing with this cc1101 thing :-)
