### ISSUE TITLE
CC1101 Terminal frozen

### ISSUE THREAD

**Issue by DIY3D** [mcore1976/cc1101-tool#19]
Hi,

I'm testing this tool with Arduino Pro mini and the CC1101.  I can type commands in the terminal but they are not visible and nothing seems to happen. 
This is the pin connection I use:

byte sck = 13; // PB5
byte miso = 11; // PB4
byte mosi = 12; // PB3
byte ss = 10; // PB2
byte gdo0 = 3; // PD3
byte gdo2 = 9; // PD5

Is SPI not working?

**Comment by mcore1976** [comment]
Arduino Pro Mini is 5V based device with ATMEGA328P chip. It has 5V TTL compatibility. If you have connected it directly to CC1101 board you probably broke it. 
If you REAAAAALY need to use this board you should lower VCC of ATMEGA chip to 3.3V.   
On 5V VCC you get the effect you have just encountered. No SPI communication.
