### ISSUE TITLE
Esp8266 WIFI AP mode 

### ISSUE THREAD

**Issue by AlistairXX** [mcore1976/cc1101-tool#24]
I don’t understand what’s wrong but my access point is open without any password  when I tried to change the code and set my own random SSID and password. The SSID did change but it was again open. No authentication what so ever. 

Telnet and everything works but still I don’t know what I’m doing wrong.

**Comment by mcore1976** [comment]
Well, it is really a problem related to ESP8266 WIFI library and I am not able to correct this. That is why the AP is set to open mode...
