### ISSUE TITLE
E07-433M20S Pa Table 20dbm

### ISSUE THREAD

**Issue by jamesbit** [mcore1976/cc1101-tool#26]
Hi all.

I have an E07-433M20S module but I can't activate 20 dbm output.

Could someone tell me if there is a way to activate a 20 dbm mode or how can I modify the SmartRC-CC1101-Driver-Lib-master library to obtain a PA Table that supports the power of 20 dbm?

Thank you.

Jamesbit.

**Comment by mcore1976** [comment]
You do not need special parameters, use the command  setpa which sets power level,

setpa XX

 the LNA is transparent and is always on in this module. It does not have special separate setting/command
