### ISSUE TITLE
Trying to run ESP-WROOM-32

### ISSUE THREAD

**Issue by petitxef** [mcore1976/cc1101-tool#29]
Hello!
First of all thanks for the code!
I'm trying to run on ESP-WROOM-32, but I see maybe is not compatible.

I tried to run with cc1101-tool-esp32.ino & cc1101-tool-esp32-wroom.ino, and on putty show this :

![screen](https://github.com/mcore1976/cc1101-tool/assets/25556673/a754a04e-c7e8-4ac9-b3d0-e04a4a98b162)

And ifif type "help" nothing happen.
I'm doing somwething wrong?

Thanks!

**Comment by mcore1976** [comment]
for me it looks like some Serial Port communication issue. Are you sure your TX cable from Serial Port is properly connected or the SPEED and PARITY is set correctly ?
