### ISSUE TITLE
cc1101 version

### ISSUE THREAD

**Issue by flakka2022** [mcore1976/cc1101-tool#3]
this code works with this version of cc1101 ? 
" https://thecaferobot.com/store/cc1101-moduale-10mw "

**Comment by mcore1976** [comment]
yes it will work without any problem
please consult this product documentation for PIN names  when trying to connect to Arduino board
https://github.com/mcore1976/cc1101-tool/blob/main/AS07-M1101S.pdf

**Comment by flakka2022** [comment]
worked perfectly fine ! thanks .
