### ISSUE TITLE
Connection closed by foreign host

### ISSUE THREAD

**Issue by AlistairXX** [mcore1976/cc1101-tool#30]
Module I’m using is wemos D1 mini. I get error escape character and connection closed by foreign host. I have tried reconnecting all wires. Re uploading the code nothing works. What may be the reason behind it?

**Comment by mcore1976** [comment]
Yes, it appears that somethings got changed in ESP8266 WIFI library in github. They may have partially broken it. My board display the same however I am able to reconnect over Telnet to 192.168.1.100 and then it starts to work ( responds to "help" commands). If you have issues with ESP8266 you can always use code version without WIFI ( set Serial port speed to 115200, 8 bit, no parity )
