### ISSUE TITLE
Terminal is frozen

### ISSUE THREAD

**Issue by Fr4nkGonzalez** [mcore1976/cc1101-tool#31]
Hi Adam,
I have installed the CC1101 Tool  using the Arduino IDE on my Raspi Pico W.
I can connect via putty to it but the windows is frozen after the conection has been established and I can not do anything.
Please find enclosed a picture.

![Putty](https://github.com/mcore1976/cc1101-tool/assets/100030917/547d6a6a-dae6-4360-b937-f2580344b168)

Do you have a hint for me?

Many Thanks
Frank
P.D. I am using a E07-M1101D from EByte

**Comment by mcore1976** [comment]
Terminal is not frozen, the CC1101 does not respond. The next message on the terminal would be "CC1101 initialized.." but it is not appearing due to incorrect wiring or some connectivity issues
