### ISSUE TITLE
.

### ISSUE THREAD

**Issue by WR117H** [mcore1976/cc1101-tool#34]
Well actually I wanna do rolljam with your tool. For example I wanna do it with 433 mhz freq. What commands should give to the input?

**your description:** [One CC1101 needs to be tuned sligtly around center frequency of the keyfob and jammer activated, while other CC1101 on other board needs to record the keyfob transmission (you need to set the RX bandwidth to lower values first not to catch jamming signal)]
### And I wanted to know that won't this make any problem if two modules are close to eachother?

**Comment by mcore1976** [comment]
On the first unit : 
1) Find the center frequency of the keyfob first (it should be around 433.92)
scan 433.5 434.0
2) Jam it but slightly around it like if the center is 433.92, jam 433.5
setmhz 433.5
jam

On the second device : 
3) set receive filter bandwith to lower width (like 250kHz) so it would not overlap with jammed frequency but catch the keyfob signal
setrxbw(250)  
4) set main keyfob frequency for the recording
setmhz 433.92
5) start recording
rxraw 50
6) display recording 
showraw

At the end you need to stop jamming and replay the recorded signal on second device
7) replay the signal
playraw 50

PS. This value "50" you need to adjust on your own
