### ISSUE TITLE
How to implement the logic converter with nano board

### ISSUE THREAD

**Issue by Parker84757** [mcore1976/cc1101-tool#35]
nevermind I figured it out. But since I am here and cannot delete this comment, can you use the pro mini board for this? also now that i have figured out how to implement the logic boards I am assuming that you could use the pro micro 5v if you use a logic level shifter?

**Comment by mcore1976** [comment]
There are to options actually 
1. Using TTL level shifter from 5V TTL -> 3.3 TTL
2. Power the Arduino board from lower voltage 3.3V through Vin pin
3. Buy a different Arduino booard like ESP8266 for 2 USD :-)

Second option is better
