### ISSUE TITLE
How to use esp8266 Acces Point mode

### ISSUE THREAD

**Issue by mehdisamadiboy** [mcore1976/cc1101-tool#36]
Hi and Thanks for developing such a library.
When I connect to Wi-Fi and enter the IP address, nothing happens.
How should I contact with esp8266 over ap wifi?

**Comment by mcore1976** [comment]
First try to upload USB version of the code for ESP8266 board to see if you did everything right. There is an info that you need to use Serial Port settings 115200 bps, 8 bit no parity. After you check if it works , strat playing with WIFI version
Lately the Espressif, makers of the ESP8266 did some changes to their Wifi library and sometimes it seems unstable on some  chips
